[package]
name = "postly"
description = "A social media platform for sharing posts and connecting with others."
version = "0.1.0"
edition = "2024"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"

[workspace.package]
version = "0.7.0"
edition = "2024"
license = "MIT"
authors = ["asm <asm2do@outlook.com>"]
repository = "https://github.com/asm2025/postly"

[dependencies]
tokio = { version = "1", features = ["full"] }

[workspace]
members = [
	"."
]

[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
lto = true
opt-level = 3
debug = false
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
