/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists audit events, newest first, with optional filters.
         * @description # Errors
         *
         *     Returns 403 for non-admins and 422 for invalid filters or paging.
         */
        get: operations["list_audit_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public OIDC settings the client needs to start a sign-in. */
        get: operations["auth_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own profile. Reachable while the account is still pending approval.
         * @description # Errors
         *
         *     Returns 401 without a valid token, 403 for a disabled account.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        /**
         * Starts deleting the caller's own account.
         * @description # Errors
         *
         *     Returns 403 while pending (or for a disabled or already-deleting account, which `Auth`
         *     rejects first), 422 when the display name does not match, 409 for the last active admin.
         */
        delete: operations["delete_me"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lists users, filtered by status, role, and a name/email search, ordered by `sort`.
         * @description # Errors
         *
         *     Returns 403 for non-admins and 422 for invalid filters or paging.
         */
        get: operations["list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One user by id.
         * @description # Errors
         *
         *     Returns 403 for non-admins and 404 for an unknown id.
         */
        get: operations["get_user"];
        put?: never;
        post?: never;
        /**
         * Starts deleting a user's account.
         * @description # Errors
         *
         *     Returns 403 for non-admins or self-deletion, 404 for an unknown id, 409 for the last
         *     admin or a user already being deleted.
         */
        delete: operations["delete_user"];
        options?: never;
        head?: never;
        /**
         * Changes one user's status or role (exactly one field per request).
         * @description # Errors
         *
         *     Returns 403 for non-admins, 404 for an unknown id, 409 for a user being deleted or the
         *     last admin, and 422 for a malformed or disallowed change.
         */
        patch: operations["update_user"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * # Errors
         * @description Returns a 503 problem naming the first failing readiness check.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEventDto: {
            actor?: components["schemas"]["UserRef"] | null;
            /** Format: date-time */
            at: string;
            /** @description Event details. Every `*_user_id` value is a `UserRef` object. */
            details: Record<string, never>;
            /** Format: uuid */
            id: string;
            ip?: string | null;
            kind: components["schemas"]["AuditEventKindDto"];
            owner?: components["schemas"]["UserRef"] | null;
            /** Format: uuid */
            request_id?: string | null;
            subject?: components["schemas"]["UserRef"] | null;
        };
        /**
         * @description Every audit event kind (`AuditEventKind` in `postit-data`); the `OpenAPI` enum the web
         *     client's kind filter is typed from. Clients must tolerate values added later.
         * @enum {string}
         */
        AuditEventKindDto: "user_provisioned" | "user_approved" | "user_disabled" | "user_enabled" | "role_changed" | "bootstrap_admin_granted" | "user_deleted" | "email_sent" | "email_dropped" | "email_failed";
        AuthConfigDto: {
            client_id: string;
            issuer: string;
            scopes: string[];
        };
        DeleteMeRequest: {
            /** @description Must equal the caller's current display name. */
            display_name: string;
        };
        /**
         * @description Machine-readable problem code (the `code` member of every problem+json body).
         * @enum {string}
         */
        ErrorCode: "unauthenticated" | "account_pending" | "account_disabled" | "forbidden" | "not_found" | "request_timeout" | "user_deleting" | "last_admin" | "idempotency_in_progress" | "version_conflict" | "payload_too_large" | "validation_failed" | "idempotency_key_reused" | "precondition_required" | "rate_limited" | "internal" | "unavailable";
        MeDto: components["schemas"]["UserDto"] & {
            /** @description The identity provider's account page (`auth.oidc.account_url`), when configured. */
            account_url?: string | null;
        };
        Page_AuditEventDto: {
            data: {
                actor?: components["schemas"]["UserRef"] | null;
                /** Format: date-time */
                at: string;
                /** @description Event details. Every `*_user_id` value is a `UserRef` object. */
                details: Record<string, never>;
                /** Format: uuid */
                id: string;
                ip?: string | null;
                kind: components["schemas"]["AuditEventKindDto"];
                owner?: components["schemas"]["UserRef"] | null;
                /** Format: uuid */
                request_id?: string | null;
                subject?: components["schemas"]["UserRef"] | null;
            }[];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        Page_UserDto: {
            data: {
                /** Format: date-time */
                approved_at?: string | null;
                /** Format: uuid */
                approved_by?: string | null;
                /** Format: date-time */
                created_at: string;
                display_name: string;
                email?: string | null;
                email_verified: boolean;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                last_seen_at?: string | null;
                role: components["schemas"]["RoleDto"];
                status: components["schemas"]["StatusDto"];
                /** Format: date-time */
                updated_at: string;
            }[];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            page_size: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Exactly one of `status` or `role`. */
        PatchUserRequest: {
            role?: components["schemas"]["RoleDto"] | null;
            status?: components["schemas"]["StatusDto"] | null;
        };
        /** @description The RFC 9457 `application/problem+json` body every error response carries. */
        ProblemDetails: {
            code: components["schemas"]["ErrorCode"];
            detail?: string | null;
            /** @description The `X-Request-Id` of the failed request, for support. */
            request_id?: string | null;
            /**
             * Format: int32
             * @description The HTTP status code.
             */
            status: number;
            title: string;
            /** @description Always `about:blank`; `code` is the discriminator. */
            type: string;
        };
        /** @enum {string} */
        RoleDto: "admin" | "member";
        /** @enum {string} */
        StatusDto: "pending" | "active" | "disabled" | "deleting";
        /** @description A postit user as admins and the user themselves see it. Profile fields come from the identity provider. */
        UserDto: {
            /** Format: date-time */
            approved_at?: string | null;
            /** Format: uuid */
            approved_by?: string | null;
            /** Format: date-time */
            created_at: string;
            display_name: string;
            email?: string | null;
            email_verified: boolean;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            role: components["schemas"]["RoleDto"];
            status: components["schemas"]["StatusDto"];
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description A user reference in the audit log. `deleted` is true for a pseudonym left by user
         *     deletion (a UUID v8, which postit never generates otherwise). `display_name` is the
         *     user's current name, or null for a pseudonym or a user no longer present.
         */
        UserRef: {
            deleted: boolean;
            display_name?: string | null;
            /** Format: uuid */
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_events: {
        parameters: {
            query?: {
                /** @description An audit event kind, e.g. `user_approved`. */
                kind?: components["schemas"]["AuditEventKindDto"];
                /** @description Inclusive lower bound (RFC 3339). */
                from?: string;
                /** @description Inclusive upper bound (RFC 3339). */
                to?: string;
                actor_user_id?: string;
                subject_user_id?: string;
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page, 1-100 (default 20). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEventDto"];
                };
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` or `forbidden` (not an admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    auth_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfigDto"];
                };
            };
            /** @description `rate_limited` (per-IP limit) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled` (disabled or deleting account) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMeRequest"];
            };
        };
        responses: {
            /** @description Deletion started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `last_admin` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_users: {
        parameters: {
            query?: {
                /** @description `pending`, `active`, `disabled`, or `deleting`. */
                status?: string;
                /** @description `admin` or `member`. */
                role?: string;
                /** @description `created_at` (oldest first) or `-created_at` (newest first, the default). */
                sort?: string;
                /** @description Case-insensitive substring of display name or email. */
                search?: string;
                /** @description 1-based page number (default 1). */
                page?: number;
                /** @description Items per page, 1-100 (default 20). */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserDto"];
                };
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` or `forbidden` (not an admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` or `forbidden` (not an admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` or `forbidden` (not an admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `user_deleting` or `last_admin` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    update_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDto"];
                };
            };
            /** @description No valid bearer token (`unauthenticated`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `account_disabled`, `account_pending` or `forbidden` (not an admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `not_found` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `user_deleting` or `last_admin` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `validation_failed` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `rate_limited`; see `Retry-After` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `internal` */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `unavailable` (signing keys not loaded yet) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A dependency is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
