[package]
name = "postly-http"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "postly_http"
path = "src/lib.rs"

[dependencies]
postly-config.workspace = true
reqwest.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
wiremock.workspace = true

[lints]
workspace = true
