[package]
name = "postit-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "postit_core"
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["serde"] }
serde.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
