FirstInstance:
  InstanceName: postit-dev
  Org:
    Name: Postit
    Human:
      UserName: admin@postit.local
      FirstName: Postit
      LastName: Admin
      Email:
        Address: admin@postit.local
        Verified: true
      Password: PostitDev1!
      PasswordChangeRequired: false
    Machine:
      Machine:
        Username: postit-bootstrap
        Name: postit xtask bootstrap
      MachineKey:
        Type: 1
        ExpirationDate: "2519-04-01T08:45:00Z"
