FirstInstance:
  InstanceName: postly-dev
  Org:
    Name: Postly
    Human:
      UserName: admin@postly.local
      FirstName: Postly
      LastName: Admin
      Email:
        Address: admin@postly.local
        Verified: true
      Password: PostlyDev1!
      PasswordChangeRequired: false
    Machine:
      Machine:
        Username: postly-bootstrap
        Name: postly xtask bootstrap
      MachineKey:
        Type: 1
        ExpirationDate: "2519-04-01T08:45:00Z"
